rootProject.name = 'Swervito64'
include ':app', ':jni:3rdParty:asmjit', ':jni:3rdParty:png', ':jni:3rdParty:zlib', ':jni:Common', ':jni:Settings', ':jni:Swervito64-rsp-core', ':jni:Swervito64-core', ':jni:Swervito64-bridge', ':jni:Swervito64-video', ':jni:Swervito64-audio', ':jni:Plugin-input', ':jni:Plugin-rsp'
